function New-MKSimplePassword {
  <#
  .SYNOPSIS
  Generates a random secure password of specified length.

  .DESCRIPTION
  New-MKSimplePassword creates a random password using a mix of uppercase and lowercase letters,
  numbers, and special characters. For readability, potentially confusing characters like 0, O, 1, l, I, 9, g, and q
  are excluded from the character set.

  .PARAMETER Length
  Specifies the length of the password to generate. Must be between 6 and 48 characters.
  Default value is 18 characters.

  .EXAMPLE
  New-MKSimplePassword

  Generates a random 18-character password using the default settings.

  .EXAMPLE
  New-MKSimplePassword -Length 12

  Generates a shorter 12-character random password.

  .EXAMPLE
  $pwd = New-MKSimplePassword -Length 24
  $pwd

  Generates a 24-character password and stores it in a variable to use later.

  .NOTES
  The passwords generated by this function contain a mix of:
  - Uppercase letters (excluding potentially confusing characters like O, I)
  - Lowercase letters (excluding potentially confusing characters like l, o, i, g, q)
  - Numbers (excluding 0, 1, 9)
  - Special characters (!@#$%^&*()_+-=)
  #>
  [CmdletBinding()]
  param (
    [Parameter(ValueFromPipelineByPropertyName)]
    [ValidateRange(6, 48)]
    [int]$Length = 18
  )

  process {
    -join ('abcdefghkmnrstuvwxyzABCDEFGHKLMNPRSTUVWXYZ23456789!@#$%^&*()_+-='.ToCharArray() | Get-Random -Count $Length)
  }
}